import 'package:flutter/material.dart';

class CentralColorScheme {
  static const ColorScheme flexSchemeLight = ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xff74a6be), 
    onPrimary: Color(0xffffffff), 
    surfaceContainerHighest: Color(0xffe3ecf2), 
    onSurface: Color(0xff1a2530), 
    onSurfaceVariant: Color(0xff607285), 
    outline: Color(0xffcbd7e2), 
    surface: Color(0xffeef7fc), 
    error: Color(0xffba1a1a),
    onError: Color(0xffffffff),
    primaryContainer: Color(0xffa5c7d9),
    onPrimaryContainer: Color(0xff122834),
    secondary: Color(0xff527a93),
    onSecondary: Color(0xffffffff),
    secondaryContainer: Color(0xffd2e4ef),
    onSecondaryContainer: Color(0xff0c1d26),
    tertiary: Color(0xff627d98),
    onTertiary: Color(0xffffffff),
    tertiaryContainer: Color(0xffe2eafd),
    onTertiaryContainer: Color(0xff0a1829),
    shadow: Color(0xff000000),
  );

  static const ColorScheme flexSchemeDark = ColorScheme(
    brightness: Brightness.dark,
    primary: Color(0xff8ec3dc), 
    onPrimary: Color(0xff162d3a), 
    surfaceContainerHighest: Color(0xff24313d),
    onSurface: Color(0xffe2ecf5), 
    onSurfaceVariant: Color(0xffa2b5c6), 
    outline: Color(0xff3f5263), 
    surface: Color(0xff141b22), 
    error: Color(0xffffb4ab),
    onError: Color(0xff690005),
    primaryContainer: Color(0xff24495c),
    onPrimaryContainer: Color(0xffcbe7f5),
    secondary: Color(0xffb6cbdc),
    onSecondary: Color(0xff203441),
    secondaryContainer: Color(0xff374b59),
    onSecondaryContainer: Color(0xffd2e7f8),
    tertiary: Color(0xffcbd6eb),
    onTertiary: Color(0xff334154),
    tertiaryContainer: Color(0xff49586c),
    onTertiaryContainer: Color(0xffe7eeff),
    shadow: Color(0xff000000),
  );
}